class AppCurrency {
  const AppCurrency(
    this.code,
    this.name, {
    this.symbol = '',
    this.decimalDigits = 2,
  });

  final String code;
  final String name;
  final String symbol;
  final int decimalDigits;

  String get displaySymbol => symbol.isEmpty ? code : symbol;
  String get searchText => '$code $name $symbol'.toLowerCase();
}

const currencies = <AppCurrency>[
  AppCurrency('BOB', 'Boliviano boliviano', symbol: 'Bs'),
  AppCurrency('USD', 'Dólar estadounidense', symbol: r'$'),
  AppCurrency('EUR', 'Euro', symbol: 'EUR'),
  AppCurrency('AED', 'Dirham de Emiratos Arabes Unidos', symbol: 'AED'),
  AppCurrency('AFN', 'Afgani afgano', symbol: 'Af'),
  AppCurrency('ALL', 'Lek albanes', symbol: 'L'),
  AppCurrency('AMD', 'Dram armenio', symbol: 'AMD'),
  AppCurrency('AOA', 'Kwanza angoleno', symbol: 'Kz'),
  AppCurrency('ARS', 'Peso argentino', symbol: r'$'),
  AppCurrency('AUD', 'Dólar australiano', symbol: r'A$'),
  AppCurrency('AWG', 'Florin arubeno', symbol: 'Afl'),
  AppCurrency('AZN', 'Manat azerbaiyano', symbol: 'AZN'),
  AppCurrency('BAM', 'Marco convertible de Bosnia', symbol: 'KM'),
  AppCurrency('BBD', 'Dolar de Barbados', symbol: r'Bds$'),
  AppCurrency('BDT', 'Taka bangladesi', symbol: 'BDT'),
  AppCurrency('BGN', 'Lev bulgaro', symbol: 'BGN'),
  AppCurrency('BHD', 'Dinar bahreini', symbol: 'BHD', decimalDigits: 3),
  AppCurrency('BIF', 'Franco burundes', symbol: 'FBu', decimalDigits: 0),
  AppCurrency('BMD', 'Dolar bermudeno', symbol: r'BD$'),
  AppCurrency('BND', 'Dolar de Brunei', symbol: r'B$'),
  AppCurrency('BRL', 'Real brasileno', symbol: r'R$'),
  AppCurrency('BSD', 'Dolar bahameno', symbol: r'B$'),
  AppCurrency('BTN', 'Ngultrum butanes', symbol: 'Nu'),
  AppCurrency('BWP', 'Pula botsuanesa', symbol: 'P'),
  AppCurrency('BYN', 'Rublo bielorruso', symbol: 'Br'),
  AppCurrency('BZD', 'Dolar beliceno', symbol: r'BZ$'),
  AppCurrency('CAD', 'Dólar canadiense', symbol: r'C$'),
  AppCurrency('CDF', 'Franco congoles', symbol: 'FC'),
  AppCurrency('CHF', 'Franco suizo', symbol: 'CHF'),
  AppCurrency('CLP', 'Peso chileno', symbol: r'$CL', decimalDigits: 0),
  AppCurrency('CNY', 'Yuan chino', symbol: 'CNY'),
  AppCurrency('COP', 'Peso colombiano', symbol: r'$CO'),
  AppCurrency('CRC', 'Colon costarricense', symbol: 'CRC'),
  AppCurrency('CUP', 'Peso cubano', symbol: r'$MN'),
  AppCurrency('CVE', 'Escudo caboverdiano', symbol: 'CVE'),
  AppCurrency('CZK', 'Corona checa', symbol: 'Kc'),
  AppCurrency('DJF', 'Franco yibutiano', symbol: 'Fdj', decimalDigits: 0),
  AppCurrency('DKK', 'Corona danesa', symbol: 'kr'),
  AppCurrency('DOP', 'Peso dominicano', symbol: r'RD$'),
  AppCurrency('DZD', 'Dinar argelino', symbol: 'DZD'),
  AppCurrency('EGP', 'Libra egipcia', symbol: 'EGP'),
  AppCurrency('ERN', 'Nakfa eritreo', symbol: 'Nfk'),
  AppCurrency('ETB', 'Birr etiope', symbol: 'Br'),
  AppCurrency('FJD', 'Dolar fiyiano', symbol: r'FJ$'),
  AppCurrency('FKP', 'Libra de las Islas Malvinas', symbol: 'FKP'),
  AppCurrency('GBP', 'Libra esterlina', symbol: 'GBP'),
  AppCurrency('GEL', 'Lari georgiano', symbol: 'GEL'),
  AppCurrency('GHS', 'Cedi ghanes', symbol: 'GHs'),
  AppCurrency('GIP', 'Libra de Gibraltar', symbol: 'GIP'),
  AppCurrency('GMD', 'Dalasi gambiano', symbol: 'D'),
  AppCurrency('GNF', 'Franco guineano', symbol: 'FG', decimalDigits: 0),
  AppCurrency('GTQ', 'Quetzal guatemalteco', symbol: 'Q'),
  AppCurrency('GYD', 'Dolar guyanes', symbol: r'G$'),
  AppCurrency('HKD', 'Dólar de Hong Kong', symbol: r'HK$'),
  AppCurrency('HNL', 'Lempira hondurena', symbol: 'L'),
  AppCurrency('HTG', 'Gourde haitiano', symbol: 'G'),
  AppCurrency('HUF', 'Forinto hungaro', symbol: 'Ft'),
  AppCurrency('IDR', 'Rupia indonesia', symbol: 'Rp'),
  AppCurrency('ILS', 'Nuevo sequel israeli', symbol: 'ILS'),
  AppCurrency('INR', 'Rupia india', symbol: 'INR'),
  AppCurrency('IQD', 'Dinar iraqui', symbol: 'IQD', decimalDigits: 3),
  AppCurrency('IRR', 'Rial irani', symbol: 'IRR'),
  AppCurrency('ISK', 'Corona islandesa', symbol: 'ISK', decimalDigits: 0),
  AppCurrency('JMD', 'Dolar jamaiquino', symbol: r'J$'),
  AppCurrency('JOD', 'Dinar jordano', symbol: 'JOD', decimalDigits: 3),
  AppCurrency('JPY', 'Yen japonés', symbol: 'JPY', decimalDigits: 0),
  AppCurrency('KES', 'Chelin keniano', symbol: 'KSh'),
  AppCurrency('KGS', 'Som kirguis', symbol: 'KGS'),
  AppCurrency('KHR', 'Riel camboyano', symbol: 'KHR'),
  AppCurrency('KMF', 'Franco comorense', symbol: 'CF', decimalDigits: 0),
  AppCurrency('KPW', 'Won norcoreano', symbol: 'KPW'),
  AppCurrency('KRW', 'Won surcoreano', symbol: 'KRW', decimalDigits: 0),
  AppCurrency('KWD', 'Dinar kuwaiti', symbol: 'KWD', decimalDigits: 3),
  AppCurrency('KYD', 'Dolar de las Islas Caiman', symbol: r'CI$'),
  AppCurrency('KZT', 'Tenge kazajo', symbol: 'KZT'),
  AppCurrency('LAK', 'Kip laosiano', symbol: 'LAK'),
  AppCurrency('LBP', 'Libra libanesa', symbol: 'LBP'),
  AppCurrency('LKR', 'Rupia de Sri Lanka', symbol: 'LKR'),
  AppCurrency('LRD', 'Dolar liberiano', symbol: r'L$'),
  AppCurrency('LSL', 'Loti lesotense', symbol: 'L'),
  AppCurrency('LYD', 'Dinar libio', symbol: 'LYD', decimalDigits: 3),
  AppCurrency('MAD', 'Dirham marroqui', symbol: 'MAD'),
  AppCurrency('MDL', 'Leu moldavo', symbol: 'MDL'),
  AppCurrency('MGA', 'Ariary malgache', symbol: 'Ar'),
  AppCurrency('MKD', 'Denar macedonio', symbol: 'MKD'),
  AppCurrency('MMK', 'Kyat birmano', symbol: 'K'),
  AppCurrency('MNT', 'Tugrik mongol', symbol: 'MNT'),
  AppCurrency('MOP', 'Pataca macaense', symbol: 'MOP'),
  AppCurrency('MRU', 'Uguiya mauritana', symbol: 'UM'),
  AppCurrency('MUR', 'Rupia mauriciana', symbol: 'MUR'),
  AppCurrency('MVR', 'Rufiyaa maldiva', symbol: 'Rf'),
  AppCurrency('MWK', 'Kwacha malaui', symbol: 'MK'),
  AppCurrency('MXN', 'Peso mexicano', symbol: r'MX$'),
  AppCurrency('MYR', 'Ringgit malayo', symbol: 'RM'),
  AppCurrency('MZN', 'Metical mozambiqueno', symbol: 'MT'),
  AppCurrency('NAD', 'Dolar namibio', symbol: r'N$'),
  AppCurrency('NGN', 'Naira nigeriana', symbol: 'NGN'),
  AppCurrency('NIO', 'Cordoba nicaraguense', symbol: r'C$'),
  AppCurrency('NOK', 'Corona noruega', symbol: 'kr'),
  AppCurrency('NPR', 'Rupia nepali', symbol: 'NPR'),
  AppCurrency('NZD', 'Dólar neozelandés', symbol: r'NZ$'),
  AppCurrency('OMR', 'Rial omani', symbol: 'OMR', decimalDigits: 3),
  AppCurrency('PAB', 'Balboa panameno', symbol: 'B/.'),
  AppCurrency('PEN', 'Sol peruano', symbol: 'S/'),
  AppCurrency('PGK', 'Kina papuana', symbol: 'K'),
  AppCurrency('PHP', 'Peso filipino', symbol: 'PHP'),
  AppCurrency('PKR', 'Rupia pakistani', symbol: 'PKR'),
  AppCurrency('PLN', 'Zloty polaco', symbol: 'zl'),
  AppCurrency('PYG', 'Guarani paraguayo', symbol: 'Gs', decimalDigits: 0),
  AppCurrency('QAR', 'Rial qatari', symbol: 'QAR'),
  AppCurrency('RON', 'Leu rumano', symbol: 'lei'),
  AppCurrency('RSD', 'Dinar serbio', symbol: 'RSD'),
  AppCurrency('RUB', 'Rublo ruso', symbol: 'RUB'),
  AppCurrency('RWF', 'Franco ruandes', symbol: 'FRw', decimalDigits: 0),
  AppCurrency('SAR', 'Rial saudi', symbol: 'SAR'),
  AppCurrency('SBD', 'Dolar de las Islas Salomon', symbol: r'SI$'),
  AppCurrency('SCR', 'Rupia seychelense', symbol: 'SCR'),
  AppCurrency('SDG', 'Libra sudanesa', symbol: 'SDG'),
  AppCurrency('SEK', 'Corona sueca', symbol: 'kr'),
  AppCurrency('SGD', 'Dólar de Singapur', symbol: r'S$'),
  AppCurrency('SHP', 'Libra de Santa Elena', symbol: 'SHP'),
  AppCurrency('SLE', 'Leone sierraleones', symbol: 'Le'),
  AppCurrency('SOS', 'Chelin somali', symbol: 'SOS'),
  AppCurrency('SRD', 'Dolar surinames', symbol: r'Sr$'),
  AppCurrency('SSP', 'Libra sursudanesa', symbol: 'SSP'),
  AppCurrency('STN', 'Dobra santotomense', symbol: 'Db'),
  AppCurrency('SYP', 'Libra siria', symbol: 'SYP'),
  AppCurrency('SZL', 'Lilangeni suazi', symbol: 'L'),
  AppCurrency('THB', 'Baht tailandes', symbol: 'THB'),
  AppCurrency('TJS', 'Somoni tayiko', symbol: 'TJS'),
  AppCurrency('TMT', 'Manat turcomano', symbol: 'TMT'),
  AppCurrency('TND', 'Dinar tunecino', symbol: 'TND', decimalDigits: 3),
  AppCurrency('TOP', 'Paanga tongano', symbol: r'T$'),
  AppCurrency('TRY', 'Lira turca', symbol: 'TRY'),
  AppCurrency('TTD', 'Dolar de Trinidad y Tobago', symbol: r'TT$'),
  AppCurrency('TWD', 'Nuevo dolar taiwanes', symbol: r'NT$'),
  AppCurrency('TZS', 'Chelin tanzano', symbol: 'TZS'),
  AppCurrency('UAH', 'Grivna ucraniana', symbol: 'UAH'),
  AppCurrency('UGX', 'Chelin ugandes', symbol: 'USh', decimalDigits: 0),
  AppCurrency('UYU', 'Peso uruguayo', symbol: r'$U'),
  AppCurrency('UZS', 'Som uzbeko', symbol: 'UZS'),
  AppCurrency('VES', 'Bolivar venezolano', symbol: 'Bs.'),
  AppCurrency('VND', 'Dong vietnamita', symbol: 'VND', decimalDigits: 0),
  AppCurrency('VUV', 'Vatu vanuatuense', symbol: 'VT', decimalDigits: 0),
  AppCurrency('WST', 'Tala samoano', symbol: r'WS$'),
  AppCurrency(
    'XAF',
    'Franco CFA de Africa Central',
    symbol: 'FCFA',
    decimalDigits: 0,
  ),
  AppCurrency('XCD', 'Dolar del Caribe Oriental', symbol: r'EC$'),
  AppCurrency(
    'XOF',
    'Franco CFA de Africa Occidental',
    symbol: 'F CFA',
    decimalDigits: 0,
  ),
  AppCurrency('XPF', 'Franco CFP', symbol: 'F CFP', decimalDigits: 0),
  AppCurrency('YER', 'Rial yemeni', symbol: 'YER'),
  AppCurrency('ZAR', 'Rand sudafricano', symbol: 'R'),
  AppCurrency('ZMW', 'Kwacha zambiano', symbol: 'ZK'),
  AppCurrency('ZWG', 'Zimbabwe Gold', symbol: 'ZiG'),
];

AppCurrency currencyByCode(String? code) {
  final normalized = code?.trim().toUpperCase();
  return currencies.firstWhere(
    (currency) => currency.code == normalized,
    orElse: () => currencies.firstWhere((currency) => currency.code == 'USD'),
  );
}

int currencyMinorFactor(String? code) {
  final digits = currencyByCode(code).decimalDigits;
  return switch (digits) {
    0 => 1,
    3 => 1000,
    _ => 100,
  };
}
